[tools]
age = "prefix:1"
awscli = "latest"
colima = "latest"
difftastic = "latest"
direnv = "latest"
elixir = "prefix:1"
erlang = "latest"
gleam = "prefix:1"
go = "prefix:1"
k9s = "latest"
lazygit = "latest"
node = "prefix:24"
pnpm = "latest"
pre-commit = "prefix:4"
pulumi = "latest"
python = "prefix:3"
terraform = "1.10.1"
terraform-docs = "latest"
terragrunt = "0.69.9"
tflint = "0.52.0"
trivy = "0.53.0"
zellij = "latest"
rust = "prefix:1"

[settings]
always_keep_download = false  # deleted after install by default
always_keep_install = false   # deleted on failure by default
asdf_compat = true            # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
erlang.compile = false
not_found_auto_install = true
# configure messages displayed when entering directories with config files
status = { missing_tools = "always", show_env = false, show_tools = false }
idiomatic_version_file_enable_tools = ["terraform"]

[tool_alias]
awscli = "https://github.com/MetricMike/asdf-awscli.git"
pulumi = "https://github.com/canha/asdf-pulumi.git"
